import X from "lucide-react/dist/esm/icons/x";
import Download from "lucide-react/dist/esm/icons/download";
import Check from "lucide-react/dist/esm/icons/check";
import Calendar from "lucide-react/dist/esm/icons/calendar";
import DollarSign from "lucide-react/dist/esm/icons/dollar-sign";
import FileText from "lucide-react/dist/esm/icons/file-text";
import Layers from "lucide-react/dist/esm/icons/layers";

export function ProposalSidebar({ proposal, isOpen, onClose }) {
    if (!proposal) return null;

    return (
        <div
            className={`fixed inset-y-0 right-0 w-[400px] bg-card border-l border-border shadow-2xl transform transition-transform duration-300 ease-in-out z-50 flex flex-col ${isOpen ? "translate-x-0" : "translate-x-full"
                }`}
        >
            {/* Header */}
            <div className="p-6 border-b border-border flex items-center justify-between bg-zinc-950/50 backdrop-blur-sm">
                <div>
                    <h2 className="text-lg font-bold flex items-center gap-2">
                        <FileText className="size-5 text-primary" />
                        Project Proposal
                    </h2>
                    <p className="text-xs text-muted-foreground mt-1">Generated by CATA AI</p>
                </div>
                <button
                    onClick={onClose}
                    className="p-2 hover:bg-white/5 rounded-full transition-colors text-muted-foreground hover:text-foreground"
                >
                    <X className="size-5" />
                </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6 space-y-8 [scrollbar-width:thin] [scrollbar-color:var(--primary)_transparent] [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-primary [&::-webkit-scrollbar-track]:bg-transparent">

                {/* Executive Summary */}
                <section>
                    <h3 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-3 flex items-center gap-2">
                        Executive Summary
                    </h3>
                    <p className="text-sm leading-relaxed text-foreground/90 bg-white/5 p-4 rounded-xl border border-white/10">
                        {proposal.summary}
                    </p>
                </section>

                {/* Services */}
                <section>
                    <h3 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-3 flex items-center gap-2">
                        <Layers className="size-4" /> Recommended Services
                    </h3>
                    <ul className="space-y-3">
                        {proposal.services?.map((service, idx) => (
                            <li key={idx} className="flex items-start gap-3 bg-card border border-border p-3 rounded-lg">
                                <Check className="size-4 text-green-500 mt-0.5 shrink-0" />
                                <span className="text-sm">{service}</span>
                            </li>
                        ))}
                    </ul>
                </section>

                {/* Timeline & Budget */}
                <div className="grid grid-cols-2 gap-4">
                    <div className="bg-white/5 p-4 rounded-xl border border-white/10">
                        <h3 className="text-xs font-semibold uppercase text-muted-foreground mb-2 flex items-center gap-1.5">
                            <Calendar className="size-3.5" /> Timeline
                        </h3>
                        <p className="text-lg font-bold text-foreground">{proposal.timeline}</p>
                    </div>
                    <div className="bg-white/5 p-4 rounded-xl border border-white/10">
                        <h3 className="text-xs font-semibold uppercase text-muted-foreground mb-2 flex items-center gap-1.5">
                            <DollarSign className="size-3.5" /> Est. Budget
                        </h3>
                        <p className="text-lg font-bold text-primary">{proposal.budget}</p>
                    </div>
                </div>

                {/* Next Steps */}
                <section>
                    <h3 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-3">
                        Next Steps
                    </h3>
                    <p className="text-sm text-muted-foreground">
                        {proposal.nextSteps || "Review the proposal and finalize the requirements to proceed with the project kickoff."}
                    </p>
                </section>
            </div>

            {/* Footer Actions */}
            <div className="p-6 border-t border-border bg-zinc-950/50 backdrop-blur-sm space-y-3">
                <button className="w-full py-3 px-4 bg-primary text-primary-foreground rounded-lg font-semibold text-sm flex items-center justify-center gap-2 hover:opacity-90 transition-opacity shadown-lg shadow-primary/20">
                    Accept Proposal
                </button>
                <button className="w-full py-3 px-4 bg-transparent border border-border text-foreground rounded-lg font-medium text-sm flex items-center justify-center gap-2 hover:bg-white/5 transition-colors">
                    <Download className="size-4" /> Download PDF
                </button>
            </div>
        </div>
    );
}
