// Service-specific question sets for the chatbot.
// Keep questions concise and ordered by impact: summary -> scope -> constraints -> assets -> extras.
export const SERVICE_QUESTION_SETS = {
  "Development & Tech": [
    {
      key: "website_requirement",
      text: "What best describes your website requirement?",
      type: "suggestion",
      suggestions: ["New website", "Revamping existing website"]
    },
    {
      key: "primary_objective",
      text: "What is the primary objective of your website?",
      type: "suggestion",
      suggestions: [
        "Generating leads",
        "Selling products or services online",
        "Building brand credibility",
        "Showcasing work or portfolio"
      ]
    },
    {
      key: "design_experience",
      text: "What type of design experience are you looking for?",
      type: "suggestion",
      suggestions: [
        "Clean and simple design",
        "Premium and modern UI",
        "Interactive or 3D-based design"
      ]
    },
    {
      key: "website_type",
      text: "What type of website do you need?",
      type: "suggestion",
      suggestions: [
        "Platform-based website (No-code / CMS)",
        "Coded website (Custom development)"
      ]
    },
    {
      key: "platform_preference",
      text: "If Platform-based website is selected, choose preferred platform(s):",
      type: "multi_select",
      suggestions: [
        "WordPress",
        "Webflow",
        "Wix",
        "Shopify",
        "Squarespace",
        "Framer",
        "Bubble",
        "Zoho Sites",
        "Google Sites",
        "Magento (Adobe Commerce)",
        "Other: ________"
      ]
    },
    {
      key: "tech_stack",
      text: "If Coded website is selected, choose preferred tech stack/technology:",
      type: "multi_select",
      suggestions: [
        "HTML, CSS, JavaScript (Static)",
        "React.js",
        "Next.js",
        "Vue.js / Nuxt.js",
        "Angular"
      ]
    },
    {
      key: "backend",
      text: "Backend (if needed):",
      type: "multi_select",
      suggestions: [
        "Node.js (Express)",
        "Python (Django / Flask / FastAPI)",
        "PHP (Laravel)",
        "Java (Spring Boot)",
        ".NET"
      ]
    },
    {
      key: "database",
      text: "Database (if needed):",
      type: "multi_select",
      suggestions: ["MySQL", "PostgreSQL", "MongoDB", "Firebase", "Supabase"]
    },
    {
      key: "ecommerce",
      text: "E-commerce (if needed):",
      type: "multi_select",
      suggestions: [
        "Custom eCommerce",
        "Stripe / Razorpay integration",
        "WooCommerce (if hybrid)"
      ]
    },
    {
      key: "additional_pages",
      text: "Every website includes: Home, About, Contact, Privacy Policy & Terms. What additional pages do you need? (Select all that apply)",
      type: "multi_select",
      suggestions: [
        "Services",
        "Products",
        "Portfolio/Gallery",
        "Testimonials",
        "Blog",
        "FAQ",
        "Pricing",
        "Shop/Store",
        "Cart/Checkout",
        "Wishlist",
        "Order Tracking",
        "Reviews/Ratings",
        "Search",
        "Book Now",
        "Account/Login",
        "Admin Dashboard",
        "User Dashboard",
        "Analytics Dashboard",
        "Notifications",
        "Chat/Support Widget",
        "Help/Support",
        "Resources",
        "Events",
        "3D Animations",
        "3D Model Viewer",
        "None"
      ]
    },
    {
      key: "content_status",
      text: "What is the status of your website content?",
      type: "suggestion",
      suggestions: ["All content is ready", "Content needs to be created"]
    },
    {
      key: "references",
      text: "Do you have any reference websites you like?",
      type: "suggestion",
      suggestions: ["Yes \\u2014 ________", "No"]
    },
    {
      key: "launch_timeline",
      text: "When would you like to launch the website?",
      type: "suggestion",
      suggestions: ["Within 2\\u20134 weeks", "Within 1\\u20132 months", "The timeline is flexible"]
    },
    {
      key: "budget_range",
      text: "What budget range are you comfortable with for this project?",
      type: "suggestion",
      suggestions: [
        "Under \\u20B925,000 (Basic website)",
        "\\u20B925,000 \\u2013 \\u20B950,000 (Standard website)",
        "\\u20B950,000 \\u2013 \\u20B91,00,000 (Advanced website)",
        "\\u20B91,00,000 \\u2013 \\u20B92,50,000 (Custom / dynamic website)",
        "\\u20B92,50,000 and above (High-end, scalable platform)"
      ]
    }
  ],
  "Lead Generation": [
    { key: "name", text: "Could you please provide your first name?", type: "text" },
    { key: "business", text: "Please briefly describe your business activities.", type: "text" },
    { key: "audience", text: "Who is your target audience?", type: "text" },
    {
      key: "volume",
      text: "What is your target volume for leads?",
      type: "suggestion",
      suggestions: ["<100", "100-500", "500+"],
    },
    { key: "offer", text: "What is your primary offer or Call to Action (CTA)?", type: "text" },
    {
      key: "channels",
      text: "Which marketing channels do you prefer?",
      type: "suggestion",
      suggestions: ["Email", "LinkedIn", "Ads", "Mixed", "Not sure"],
    },
    { key: "geo", text: "What is your target geographic location?", type: "text" },
    { key: "budget", text: "What is your estimated budget? Please enter a single amount in INR.", type: "text" },
    { key: "timeline", text: "When would you like to commence the campaign?", type: "text" },
    { key: "assets", text: "Please share any relevant case studies or landing page links.", type: "text" },
  ],

  "Video Services": [
    { key: "name", text: "Could you please provide your first name?", type: "text" },
    {
      key: "video_type",
      text: "What specific type of video production do you require?",
      type: "suggestion",
      suggestions: [
        "Promo/Marketing",
        "Social content",
        "YouTube/Vlog",
        "Corporate/Event",
        "Explainer/Animated",
        "Other",
      ],
    },
    {
      key: "goal",
      text: "What is the primary objective of this video?",
      type: "suggestion",
      suggestions: ["Awareness", "Leads", "Engagement", "Launch"],
    },
    {
      key: "footage",
      text: "Do you have existing footage, or is production required?",
      type: "suggestion",
      suggestions: ["Yes, have footage", "Need production", "Not sure"],
    },
    {
      key: "length",
      text: "What is the desired duration of the video?",
      type: "suggestion",
      suggestions: ["<30s", "30-60s", "1-3m", "3m+"],
    },
    {
      key: "style",
      text: "What is the preferred style or tone?",
      type: "suggestion",
      suggestions: ["Corporate", "Fun", "Emotional", "Cinematic", "Informative"],
    },
    {
      key: "usage",
      text: "On which platforms will the video be distributed?",
      type: "suggestion",
      suggestions: ["Website", "YouTube", "Instagram", "LinkedIn", "TikTok", "Other"],
    },
    {
      key: "budget",
      text: "What is your estimated budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "What is your desired timeline for delivery?",
      type: "suggestion",
      suggestions: ["1 week", "2-4 weeks", "1-2 months", "Flexible"],
    },
    { key: "references", text: "Please share any reference links or examples.", type: "text" },
  ],

  "Travel Services": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "destination", text: "Where to?", type: "text" },
    {
      key: "dates",
      text: "Travel dates?",
      type: "suggestion",
      suggestions: ["Specific", "Flexible"],
    },
    {
      key: "people",
      text: "How many travelers?",
      type: "suggestion",
      suggestions: ["1", "2", "Family (3-5)", "Group (6+)"],
    },
    {
      key: "trip_purpose",
      text: "Trip purpose?",
      type: "suggestion",
      suggestions: ["Vacation", "Honeymoon", "Business", "Family", "Adventure", "Cultural"],
    },
    {
      key: "experience",
      text: "Preferred vibe?",
      type: "suggestion",
      suggestions: ["Relaxing", "Adventure", "Cultural", "Beach", "City", "Nature"],
    },
    {
      key: "stay",
      text: "Stay type?",
      type: "suggestion",
      suggestions: ["Budget", "3-4 star", "Luxury", "Homestay/Airbnb", "Decide later"],
    },
    {
      key: "budget",
      text: "What is the budget per person? Please enter a single amount in INR.",
      type: "text",
    },
    { key: "extras", text: "Need flights/transfers/tours?", type: "text" },
    { key: "notes", text: "Special requests (diet, accessibility, activities)?", type: "text" },
  ],

  "Event Management": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    {
      key: "event_type",
      text: "Event type?",
      type: "suggestion",
      suggestions: [
        "Wedding/Engagement",
        "Corporate/Conference",
        "Birthday",
        "Product Launch",
        "Festival/Concert",
        "Other",
      ],
    },
    { key: "date", text: "Event date (or tentative)?", type: "text" },
    { key: "location", text: "Event location?", type: "text" },
    {
      key: "guests",
      text: "Guest count?",
      type: "suggestion",
      suggestions: ["<50", "50-100", "100-300", "300-500", "500+"],
    },
    {
      key: "scope",
      text: "Scope needed?",
      type: "suggestion",
      suggestions: ["Full service", "Venue only", "Decor only", "Already arranged"],
    },
    { key: "theme", text: "Theme or style?", type: "text" },
    {
      key: "media",
      text: "Need photo/video/AV?",
      type: "suggestion",
      suggestions: ["Yes", "No", "Not sure"],
    },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    { key: "notes", text: "Special requests or must-haves?", type: "text" },
  ],

  "Visa & Passport": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    {
      key: "service_type",
      text: "What do you need?",
      type: "suggestion",
      suggestions: [
        "New passport",
        "Passport renewal",
        "Lost/Damaged replacement",
        "Visa application",
        "Visa extension/renewal",
        "Other",
      ],
    },
    { key: "country", text: "Which country are you applying for?", type: "text" },
    { key: "nationality", text: "Your nationality?", type: "text" },
    {
      key: "purpose",
      text: "Travel purpose?",
      type: "suggestion",
      suggestions: ["Tourism", "Business", "Study", "Family", "Migration", "Medical", "Other"],
    },
    { key: "travel_date", text: "Planned travel date?", type: "text" },
    {
      key: "docs",
      text: "Docs ready?",
      type: "suggestion",
      suggestions: ["All ready", "Some ready", "Need help"],
    },
    {
      key: "speed",
      text: "Processing speed?",
      type: "suggestion",
      suggestions: ["Regular", "Express/Urgent"],
    },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    { key: "notes", text: "Special notes or requests?", type: "text" },
  ],

  "Insurance Services": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    {
      key: "type",
      text: "Insurance type?",
      type: "suggestion",
      suggestions: ["Health", "Life", "Travel", "Auto", "Home/Property", "Business", "Other"],
    },
    {
      key: "usage",
      text: "Who is it for?",
      type: "suggestion",
      suggestions: ["Individual", "Family", "Business"],
    },
    {
      key: "coverage",
      text: "Coverage amount?",
      type: "suggestion",
      suggestions: [
        "Under INR 8,30,000",
        "INR 8,30,000-41,50,000",
        "INR 41,50,000-83,00,000",
        "INR 83,00,000+",
        "Not sure",
      ],
    },
    {
      key: "duration",
      text: "Policy duration?",
      type: "suggestion",
      suggestions: ["<1 year", "1-5 years", "5+ years", "Lifetime"],
    },
    {
      key: "addons",
      text: "Add-ons/riders?",
      type: "suggestion",
      suggestions: ["Yes", "No", "Not sure"],
    },
    {
      key: "budget",
      text: "What is your budget plan? Please enter a single amount in INR (per month if applicable).",
      type: "text",
    },
    {
      key: "start",
      text: "When to start coverage?",
      type: "suggestion",
      suggestions: ["Immediately", "Within a week", "Within a month", "Exploring"],
    },
    { key: "info", text: "Key details (age/vehicle/property/etc.)?", type: "text" },
    { key: "notes", text: "Special requests?", type: "text" },
  ],

  "Real Estate": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    {
      key: "service_type",
      text: "Looking to buy/sell/rent?",
      type: "suggestion",
      suggestions: ["Buy", "Sell", "Rent/Lease", "Management", "Investment"],
    },
    {
      key: "category",
      text: "Property category?",
      type: "suggestion",
      suggestions: ["Residential", "Commercial", "Land", "Other"],
    },
    { key: "city", text: "City/area?", type: "text" },
    {
      key: "property_type",
      text: "Property type?",
      type: "suggestion",
      suggestions: ["Apartment", "House/Villa", "Office", "Retail", "Plot/Land", "Other"],
    },
    { key: "beds", text: "Bedrooms (if residential)?", type: "text" },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "When to move/close?",
      type: "suggestion",
      suggestions: ["Immediately", "3 months", "6 months", "Exploring"],
    },
    { key: "amenities", text: "Must-have amenities?", type: "text" },
    { key: "notes", text: "Any links or notes to share?", type: "text" },
  ],

  "HR Services": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "company", text: "Company name?", type: "text" },
    { key: "location", text: "Company location?", type: "text" },
    {
      key: "service_type",
      text: "Which HR services?",
      type: "suggestion",
      suggestions: [
        "Recruitment",
        "Payroll",
        "Outsourced HR",
        "Onboarding",
        "Performance",
        "Training",
        "Compliance",
        "Other",
      ],
    },
    {
      key: "duration",
      text: "One-time or ongoing?",
      type: "suggestion",
      suggestions: ["One-time", "Ongoing"],
    },
    {
      key: "size",
      text: "Team size?",
      type: "suggestion",
      suggestions: ["1-10", "11-50", "51-200", "200+"],
    },
    { key: "challenge", text: "Biggest HR challenge now?", type: "text" },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "When to start?",
      type: "suggestion",
      suggestions: ["Immediately", "1 month", "3 months", "Flexible"],
    },
    { key: "notes", text: "Special requests?", type: "text" },
  ],

  "Influencer Services": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "brand", text: "Brand/company name?", type: "text" },
    {
      key: "role",
      text: "Are you a brand or influencer?",
      type: "suggestion",
      suggestions: ["Brand", "Influencer"],
    },
    {
      key: "service_type",
      text: "What do you need?",
      type: "suggestion",
      suggestions: [
        "Full campaign",
        "Search & outreach",
        "UGC content",
        "Collabs/Sponsorships",
        "Growth strategy",
        "Other",
      ],
    },
    {
      key: "goal",
      text: "Main goal?",
      type: "suggestion",
      suggestions: ["Awareness", "Promotion", "Leads/Sales", "Engagement", "Event", "App downloads"],
    },
    {
      key: "platforms",
      text: "Platforms?",
      type: "suggestion",
      suggestions: ["Instagram", "TikTok", "YouTube", "Facebook", "LinkedIn", "X/Twitter", "Other"],
    },
    {
      key: "influencer_size",
      text: "Influencer size?",
      type: "suggestion",
      suggestions: ["Nano", "Micro", "Macro", "Celebrity", "Open"],
    },
    {
      key: "budget",
      text: "What is the campaign budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "Launch timeline?",
      type: "suggestion",
      suggestions: ["Immediately", "1 month", "3 months", "Exploring"],
    },
    { key: "references", text: "Any past campaigns or examples?", type: "text" },
  ],

  "Writing & Content": [
    { key: "name", text: "Could you please provide your first name?", type: "text" },
    {
      key: "service_type",
      text: "What specific type of content do you require?",
      type: "suggestion",
      suggestions: [
        "Blogs/Articles",
        "Website copy",
        "SEO content",
        "Social posts",
        "Product descriptions",
        "Emails/Newsletters",
        "Scripts",
        "Technical/Ghostwriting",
      ],
    },
    { key: "goal", text: "What is the primary goal of this content?", type: "text" },
    { key: "audience", text: "Who is the intended audience?", type: "text" },
    {
      key: "tone",
      text: "What is the desired tone or style?",
      type: "suggestion",
      suggestions: ["Professional", "Friendly", "Persuasive", "Educational", "Storytelling"],
    },
    {
      key: "word_count",
      text: "What is the required word count?",
      type: "suggestion",
      suggestions: ["<500", "500-1,000", "1,000-2,000", "2,000+", "Not sure"],
    },
    {
      key: "seo",
      text: "Do you require SEO optimization or keyword integration?",
      type: "suggestion",
      suggestions: ["Yes", "No", "Maybe"],
    },
    {
      key: "budget",
      text: "What is your estimated budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "What is your desired timeline for delivery?",
      type: "suggestion",
      suggestions: ["1-3 days", "1 week", "2-3 weeks", "Flexible"],
    },
    { key: "references", text: "Please share any reference links or writing samples.", type: "text" },
  ],

  "Digital Marketing": [
    { key: "name", text: "Could you please provide your first name?", type: "text" },
    { key: "business_name", text: "What is the name of your business?", type: "text" },
    { key: "website", text: "What is your website URL (if applicable)?", type: "text" },
    {
      key: "service_type",
      text: "Which digital marketing services are you interested in?",
      type: "suggestion",
      suggestions: ["SEO", "Social Media Marketing", "Google Ads", "Meta Ads", "GMB Optimization", "Content Marketing", "Full Strategy"],
    },
    { key: "goals", text: "What are your primary marketing goals (e.g., brand awareness, leads, sales)?", type: "text" },
    { key: "audience", text: "Who is your target audience?", type: "text" },
    { key: "competitors", text: "Who are your main competitors?", type: "text" },
    {
      key: "budget",
      text: "What is your monthly marketing budget? Please enter a single amount in INR.",
      type: "text",
    },
    { key: "timeline", text: "When would you like to start?", type: "text" },
    { key: "notes", text: "Do you have any specific requirements or questions?", type: "text" },
  ],

  "Business & Finance": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "company", text: "Business name?", type: "text" },
    { key: "location", text: "Business location?", type: "text" },
    {
      key: "service_type",
      text: "What service do you need?",
      type: "suggestion",
      suggestions: [
        "Registration/Setup",
        "Accounting/Bookkeeping",
        "Tax filing",
        "Payroll",
        "Planning/Budgeting",
        "Consulting/Strategy",
        "Funding/Loans",
        "Audit/Compliance",
        "Other",
      ],
    },
    {
      key: "stage",
      text: "Business stage?",
      type: "suggestion",
      suggestions: ["New", "Established", "Personal"],
    },
    { key: "goal", text: "Top goal/challenge?", type: "text" },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "When to start?",
      type: "suggestion",
      suggestions: ["Immediately", "2 weeks", "1 month", "Flexible"],
    },
    { key: "systems", text: "Do you use any finance tools now?", type: "text" },
    { key: "notes", text: "Any specific notes?", type: "text" },
  ],

  "Legal & Compliance": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "company", text: "Company/organization name?", type: "text" },
    { key: "location", text: "Where are you based?", type: "text" },
    {
      key: "service_type",
      text: "What legal help do you need?",
      type: "suggestion",
      suggestions: [
        "Incorporation",
        "Contracts",
        "IP (TM/Copyright/Patent)",
        "Advisory",
        "Employment/HR",
        "Tax/Compliance",
        "Privacy/Data",
        "Disputes/Arbitration",
        "Other",
      ],
    },
    {
      key: "matter_type",
      text: "Is this business or personal?",
      type: "suggestion",
      suggestions: ["New business", "Existing business", "Personal"],
    },
    { key: "brief", text: "Short requirement summary.", type: "text" },
    {
      key: "structure",
      text: "Business structure?",
      type: "suggestion",
      suggestions: ["Sole prop", "Partnership/LLP", "Private Ltd", "Public Ltd", "Nonprofit", "Other"],
    },
    { key: "industry", text: "Industry?", type: "text" },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    { key: "notes", text: "Any specific regulations or notes?", type: "text" },
  ],

  "Education & Training": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    {
      key: "training_type",
      text: "What training are you seeking?",
      type: "suggestion",
      suggestions: [
        "Academic",
        "Test prep",
        "Professional skills",
        "Tech/IT",
        "Soft skills",
        "Language",
        "Corporate",
        "Other",
      ],
    },
    {
      key: "for_whom",
      text: "Who is it for?",
      type: "suggestion",
      suggestions: ["Myself", "My child", "My organization", "Other"],
    },
    { key: "goal", text: "Main learning goal?", type: "text" },
    {
      key: "experience",
      text: "Current level?",
      type: "suggestion",
      suggestions: ["Beginner", "Intermediate", "Advanced"],
    },
    {
      key: "format",
      text: "Preferred format?",
      type: "suggestion",
      suggestions: ["Online live", "Recorded", "In-person", "Hybrid"],
    },
    {
      key: "schedule",
      text: "Schedule?",
      type: "suggestion",
      suggestions: ["Weekdays", "Weekends", "Evenings", "Flexible"],
    },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "When to start?",
      type: "suggestion",
      suggestions: ["Immediately", "Within a month", "Flexible"],
    },
    { key: "notes", text: "Any subjects or notes to share?", type: "text" },
  ],

  "Lifestyle & Personal": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    {
      key: "service_type",
      text: "What type of coaching/service?",
      type: "suggestion",
      suggestions: [
        "Life coaching",
        "Fitness",
        "Nutrition",
        "Styling",
        "Mental wellness",
        "Relationships",
        "Personal development",
        "Other",
      ],
    },
    { key: "goal", text: "Main goal to achieve?", type: "text" },
    { key: "challenge", text: "Biggest current challenge?", type: "text" },
    {
      key: "format",
      text: "Session format?",
      type: "suggestion",
      suggestions: ["Online", "In-person", "Hybrid"],
    },
    {
      key: "frequency",
      text: "How often?",
      type: "suggestion",
      suggestions: ["Weekly", "Bi-weekly", "Monthly", "Custom"],
    },
    {
      key: "duration",
      text: "Program length?",
      type: "suggestion",
      suggestions: ["1 month", "3 months", "6 months", "Ongoing"],
    },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    { key: "preferences", text: "Special considerations or preferences?", type: "text" },
    { key: "references", text: "Any links or past plans to share?", type: "text" },
  ],

  "Customer Support": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "company", text: "Company/brand name?", type: "text" },
    {
      key: "support_type",
      text: "Support type needed?",
      type: "suggestion",
      suggestions: [
        "Live chat",
        "Email",
        "Phone/Call center",
        "Technical",
        "Social",
        "Helpdesk",
        "Multi-channel",
        "Other",
      ],
    },
    {
      key: "system",
      text: "Existing system or new setup?",
      type: "suggestion",
      suggestions: ["Existing", "New"],
    },
    {
      key: "volume",
      text: "Request volume?",
      type: "suggestion",
      suggestions: ["<50/day", "50-200/day", "200-500/day", "500+/day", "Not sure"],
    },
    {
      key: "hours",
      text: "Operating hours?",
      type: "suggestion",
      suggestions: ["Business hours", "24/7", "Weekends included", "Flexible"],
    },
    { key: "tools", text: "Tools you use (e.g., Zendesk, Freshdesk)?", type: "text" },
    {
      key: "agents",
      text: "Need agents, training, or both?",
      type: "suggestion",
      suggestions: ["Provide agents", "Train team", "Both"],
    },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR (per month if applicable).",
      type: "text",
    },
    { key: "notes", text: "Top priority or special notes?", type: "text" },
  ],

  "Administrative Services": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "company", text: "Company/organization name?", type: "text" },
    {
      key: "service_type",
      text: "What admin help do you need?",
      type: "suggestion",
      suggestions: [
        "Virtual assistant",
        "Data entry",
        "Scheduling",
        "Email/inbox",
        "File/Database",
        "Travel bookings",
        "Project coordination",
        "Client communication",
        "Other",
      ],
    },
    {
      key: "scope",
      text: "One-time or ongoing?",
      type: "suggestion",
      suggestions: ["One-time", "Ongoing"],
    },
    { key: "tasks", text: "Main tasks/challenges?", type: "text" },
    {
      key: "hours",
      text: "Hours per week?",
      type: "suggestion",
      suggestions: ["<10", "10-20", "20-40", "40+"],
    },
    {
      key: "timezone",
      text: "Timezone/schedule needs?",
      type: "suggestion",
      suggestions: ["Specific", "No preference", "Flexible"],
    },
    {
      key: "budget",
      text: "What is your monthly budget? Please enter a single amount in INR.",
      type: "text",
    },
    { key: "tools", text: "Tools you use (Google, Office, CRM, etc.)?", type: "text" },
    { key: "notes", text: "Any special instructions?", type: "text" },
  ],

  "Audio Services": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    {
      key: "service_type",
      text: "Audio service needed?",
      type: "suggestion",
      suggestions: [
        "Voiceover",
        "Podcast editing",
        "Sound design/SFX",
        "Music/Scoring",
        "Mixing/Mastering",
        "Restoration",
        "Audiobook",
        "Jingle/Ad",
        "Other",
      ],
    },
    { key: "goal", text: "Project goal/use case?", type: "text" },
    {
      key: "tone",
      text: "Tone/mood?",
      type: "suggestion",
      suggestions: ["Corporate", "Friendly", "Energetic", "Calm", "Dramatic", "Other"],
    },
    {
      key: "talent",
      text: "Need voice talent?",
      type: "suggestion",
      suggestions: ["Male", "Female", "Either", "Accent-specific", "No"],
    },
    { key: "length", text: "Duration or number of files?", type: "text" },
    {
      key: "format",
      text: "Output format?",
      type: "suggestion",
      suggestions: ["MP3", "WAV", "AIFF", "Not sure"],
    },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "Delivery timeline?",
      type: "suggestion",
      suggestions: ["3 days", "1 week", "2-3 weeks", "Flexible"],
    },
    { key: "references", text: "Reference audio links?", type: "text" },
  ],

  "Digital Marketing": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "brand", text: "Brand/company name?", type: "text" },
    { key: "business_info", text: "1-2 lines on your business.", type: "text" },
    {
      key: "goals",
      text: "Top marketing goal?",
      type: "suggestion",
      suggestions: ["Traffic", "Leads/Sales", "Awareness", "Launch", "Other"],
    },
    {
      key: "services",
      text: "Which services?",
      type: "suggestion",
      suggestions: ["Social", "SEO", "Google/Meta Ads", "Email", "Content", "Full strategy"],
    },
    { key: "audience", text: "Target audience (who/where)?", type: "text" },
    {
      key: "budget",
      text: "What is your monthly budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "When to start?",
      type: "suggestion",
      suggestions: ["Immediately", "2 weeks", "Next month", "Flexible"],
    },
    { key: "assets", text: "Website or socials links?", type: "text" },
    { key: "references", text: "Any competitor or reference links?", type: "text" },
  ],

  "Creative & Design": [
    { key: "name", text: "Hi! What's your first name?", type: "text" },
    { key: "brand", text: "Brand or project name?", type: "text" },
    {
      key: "service_type",
      text: "What design help do you need?",
      type: "suggestion",
      suggestions: [
        "Logo/Branding",
        "Social/Graphics",
        "Web/UI",
        "Packaging/Print",
        "Motion",
        "Other",
      ],
    },
    { key: "vision", text: "1-2 lines on the project vision.", type: "text" },
    {
      key: "style",
      text: "Preferred style?",
      type: "suggestion",
      suggestions: ["Modern", "Bold/Colorful", "Elegant", "Playful", "Corporate", "Not sure"],
    },
    {
      key: "deliverables",
      text: "Needed deliverables?",
      type: "suggestion",
      suggestions: ["Logo kit", "Social templates", "Website/UI", "Print", "Ads", "Other"],
    },
    {
      key: "budget",
      text: "What is your budget? Please enter a single amount in INR.",
      type: "text",
    },
    {
      key: "timeline",
      text: "Timeline?",
      type: "suggestion",
      suggestions: ["1 week", "2-4 weeks", "1-2 months", "Flexible"],
    },
    { key: "assets", text: "Any existing logo/colors/brand guide?", type: "text" },
    { key: "references", text: "Reference links you like?", type: "text" },
  ],

  "Branding (Naming, Logo & Brand Identity)": [
    {
      key: "name",
      text: "Hi! I see you're interested in Branding (Naming, Logo & Brand Identity). What's your name? Let's get started.",
      type: "text",
    },
    {
      key: "brand_stage",
      text: "At what stage is your brand currently?",
      type: "suggestion",
      suggestions: ["New brand", "Existing brand", "Rebranding"],
    },
    {
      key: "naming_support",
      text: "Do you require assistance with finalising or creating your brand name?",
      type: "suggestion",
      suggestions: [
        "No, the brand name is already finalised",
        "Yes, Few name suggestions",
        "Yes, Complete naming strategy",
      ],
    },
    {
      key: "brand_perception",
      text: "How would you like your brand to be perceived by your audience?",
      type: "suggestion",
      suggestions: [
        "Professional and trustworthy",
        "Modern and bold",
        "Premium and minimal",
        "Youthful and energetic",
      ],
    },
    {
      key: "target_audience",
      text: "Who is your primary target audience?",
      type: "suggestion",
      suggestions: [
        "Businesses (B2B)",
        "Consumers (B2C)",
        "Direct-to-consumer (D2C)",
        "A mix of different audiences",
      ],
    },
    {
      key: "branding_usage",
      text: "Where will this branding be used most frequently?",
      type: "suggestion",
      suggestions: [
        "Website and digital platforms",
        "Social media channels",
        "Packaging and print materials",
        "Across all platforms",
      ],
    },
    {
      key: "reference_brands",
      text: "Do you have any reference brands whose style you admire?",
      type: "suggestion",
      suggestions: ["Yes -", "No"],
    },
    {
      key: "deliverables",
      text: "Which branding deliverables are you looking for? (multiple options)",
      type: "multi_select",
      suggestions: [
        "Brand strategy & positioning",
        "Brand vision, mission & values",
        "Target audience & buyer persona",
        "Competitor & market analysis",
        "Brand tone of voice",
        "Logo design (primary, secondary, icon)",
        "Color palette",
        "Typography system",
        "Visual identity elements & patterns",
        "Iconography style",
        "Image / illustration style",
        "Brand guidelines / brand book",
        "Business card design",
        "Letterhead & stationery",
        "Email signature",
        "Pitch deck / presentation template",
        "Brochure / flyer design",
        "Social media profile & cover designs",
        "Social media post templates",
        "Website UI brand direction",
        "Brand messaging & brand story",
        "Complete brand identity kit",
      ],
    },
    {
      key: "timeline",
      text: "What is your preferred timeline for completing the branding work?",
      type: "suggestion",
      suggestions: ["Within 2 weeks", "Within 3-4 weeks", "Within 1-2 months"],
    },
    {
      key: "creative_freedom",
      text: "How much creative freedom would you like to give the design team?",
      type: "suggestion",
      suggestions: [
        "Full creative freedom",
        "Some guidelines -",
        "Strict brand guidelines -",
      ],
    },
    {
      key: "budget_range",
      text: "Which budget level best represents your expectation for this project?",
      type: "suggestion",
      suggestions: [
        "Under INR 25,000",
        "INR 25,000 - 50,000",
        "INR 50,000 - 1,00,000",
        "INR 1,00,000 and above",
      ],
    },
  ],
};

export const DEFAULT_QUESTIONS = [
  { key: "name", text: "Hi! What's your first name?", type: "text" },
  { key: "summary", text: "Give a 1-2 line summary of what you need.", type: "text" },
  { key: "goal", text: "Main goal or outcome?", type: "text" },
  { key: "budget", text: "What is your budget? Please enter a single amount in INR.", type: "text" },
  { key: "timeline", text: "Timeline?", type: "text" },
  { key: "references", text: "Any links or references?", type: "text" },
];
